### ISSUE TITLE
No package for 14.04?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [artmg/nixnote2-packaging#12]
After adding ppa to Ubuntu 14.04 I am getting 404 when trying to install.

**Comment by artmg** [comment]
The [Launchpad Recipes](https://code.launchpad.net/~nixnote/+recipe/nixnote2-daily) include a build for Trusty 14.04 LTS version. The [PPA](https://code.launchpad.net/~nixnote/+archive/ubuntu/nixnote2-daily) also shows it there.

Could you please indicate the commands you use and the exact error message(s) returned
Thanks

**Comment by vitaly-zdanevich** [comment]
$ sudo apt-get install --only-upgrade nixnote2 
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-3.13.0-87 linux-headers-3.13.0-87-generic
  linux-image-3.13.0-87-generic linux-image-extra-3.13.0-87-generic
Use 'apt-get autoremove' to remove them.
The following packages will be upgraded:
  nixnote2
1 upgraded, 0 newly installed, 0 to remove and 62 not upgraded.
Need to get 2,742 kB of archives.
After this operation, 15.4 kB of additional disk space will be used.
Err http://ppa.launchpad.net/nixnote/nixnote2-daily/ubuntu/ trusty/main nixnote2 all 2.0-beta-8-0+783+34+201608212001~ubuntu14.04.1
  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/nixnote/nixnote2-daily/ubuntu/pool/main/n/nixnote2/nixnote2_2.0-beta-8-0+783+34+201608212001~ubuntu14.04.1_all.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by artmg** [comment]
Do you have an option in your **Preferences** for **Software and Updates**, on the **Updates** tab, for **Unsupported Updates (trusty-backports)**? If so please **Check** this option, then close the settings and Reload the sources (equivalent to doing  `sudo apt-get update`  to refresh the changes).
Then retry the install / upgrade.

**Comment by artmg** [comment]
FYI It might be that simply doing a 
`sudo apt-get update`
`sudo apt-get install nixnote2`
might work now. 

I have just checked and inside http://ppa.launchpad.net/nixnote/nixnote2-daily/ubuntu/dists/trusty/main/ there _are_ packages for at least i386 and amd64 architectures, built 12th Sep. These point to http://ppa.launchpad.net/nixnote/nixnote2-daily/ubuntu/pool/main/n/nixnote2/nixnote2_2.0-beta-8-0+790+34+201609120601~ubuntu14.04.1_all.deb which at the time of writing CAN be found. Ergo it should "just work" now.

I'm not sure why it tried to get the Build 783 file in the error message you have above, but hopefully the issue has sorted itself out now.
