### ISSUE TITLE
Problem running NixNote2 on Trusty

### ISSUE THREAD

**Issue by MaciekTalaska** [artmg/nixnote2-packaging#13]
I am having problem using NixNote2 on Trusy (14.04). It installs without problems, but when about to start it complaints about libcurl.so.4: 
`nixnote2: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory`

I've tried to make a link to the version of the libcurl.so.4 that I have on my system, but then I got the following error: 
`nixnote2: error while loading shared libraries: libcurl.so.4: wrong ELF class: ELFCLASS64` 

I assumed, that I should have libcurl.so.4 in 32bit version. I am not sure how to do that (tried installing libcurl4:i386, but that would replace a lot of my 64 bit packages...). And even if I fix this error (I linked to the libcurl.so.4 used by other app, which has the lib in its own folder) I am facing another problem: 
`nixnote2: error while loading shared libraries: libpoppler-qt4.so.4: cannot open shared object file: No such file or directory`

Can anyone help with this please?

Note: NixNote2 works well on 16.04.

**Comment by artmg** [comment]
Judging from your message, you have probably done the usual diagnostics yourself (and tried to fix them with links), but I'd appreciate it if you could share some of that with others.  Please paste the output from

```
dpkg -s nixnote2 | grep Version
dpkg -S libcurl.so
locate libcurl.so
```

Thanks
Art

---

### other Diagnostic research Notes:

_for reference_
In our **debian/control** file we have the following included:

```
(Runtime) Depends: libpoppler-qt4-4, libcurl3
Build-Depends: libpoppler-qt4-dev, libcurl4-openssl-dev
```

I vaguely remember a reason for this disparity in version libcurl version for build and runtime when originally packaging nixnote2, and I'd have to look this up, but if this were the issue, it seems odd that it would only affect Trusty.  Maybe I should look through the Trusty Compile logs 

Back at the time of Trusty, in the upstream source package,  there was no curl only this one ...
`Depends: libpoppler-qt4-4`

This is probably not related to https://sourceforge.net/p/nevernote/bugs/250/

**Comment by MaciekTalaska** [comment]
dpkg -s nixnote2 | grep Version
`Version: 2.0-beta-8-0+793+34+201609190202~ubuntu14.04.1`

dpkg -S libcurl.so
`libcurl3:amd64: /usr/lib/x86_64-linux-gnu/libcurl.so.3`
`libcurl3:amd64: /usr/lib/x86_64-linux-gnu/libcurl.so.4`
`libcurl3:amd64: /usr/lib/x86_64-linux-gnu/libcurl.so.4.3.0`

locate libcurl.so
`/usr/lib/x86_64-linux-gnu/libcurl.so.3`
`/usr/lib/x86_64-linux-gnu/libcurl.so.4`
`/usr/lib/x86_64-linux-gnu/libcurl.so.4.3.0`

I am not sure, but maybe some info on libpopler-qt4 may be helpful:

dpkg -S libpoppler-qt4.so
`libpoppler-qt4-4:amd64: /usr/lib/x86_64-linux-gnu/libpoppler-qt4.so.4`
`libpoppler-qt4-4:amd64: /usr/lib/x86_64-linux-gnu/libpoppler-qt4.so.4.3.0`

locate libpoppler-qt4.so
`/usr/lib/x86_64-linux-gnu/libpoppler-qt4.so.4`
`/usr/lib/x86_64-linux-gnu/libpoppler-qt4.so.4.3.0`

**Comment by artmg** [comment]
Thanks Maciek, 
unfortunately it appears that only the i386 nicnote2 package was built at that version for Trusty https://launchpad.net/~nixnote/+archive/ubuntu/nixnote2-daily/+sourcepub/6946253/+listing-archive-extra 
However your system must be amd64 from your diagnostics above.

More recent distribution series (like Vivid) had the amd64 package built, but not Trusty. https://launchpad.net/~nixnote/+archive/ubuntu/nixnote2-daily/+packages

This is almost certainly the cause of your issues, but next I need to work my way around the launchpad autobuilds to find out why, and more importantly how to fix this.

**Comment by artmg** [comment]
In the meantime, rather than using the PPA, can you manage to download the DEB package directly from http://ppa.launchpad.net/nixnote/nixnote2-daily/ubuntu/pool/main/n/nixnote2/nixnote2_2.0-beta-8-0+793+34+201609190202~ubuntu14.04.1_all.deb 
then 
`sudo apt-get remove nixnote2`
then double click the DEB file or

```
dpkg -i <path to DEB file>
sudo apt-get install -f
```

**Comment by MaciekTalaska** [comment]
Artmg,

Yes, you're right, I'm on 64-bit version of Kubuntu. I am not sure why I haven't stated that explicitly in the first post.

I have followed the steps you've mentioned, but with no luck - i.e. after removing the version of nixnote2 installed from PPA and installing the .deb you've pointed me to, I am still getting the following error:

`Version: 2.0-beta-8-0+793+34+201609190202~ubuntu14.04.1`

Is there anything else I may try to have NixNote2 running on my system?

**Comment by chemeris** [comment]
I'm facing the same issue with Ubuntu 14.04 64-bit. I solved it with `sudo apt install libcurl3:i386 libpoppler-qt4-4:i386`, but this is ugly. It would be great to have a proper 64-bit package built.

I think you have an issue with Debian `rules` file, because the package says `Architecture: all` which is not correct.

**Comment by artmg** [comment]
Thanks @chemeris - I hope that your workaround will work around @MaciekTalaska 's issue, and I appreciate your pointer as to where the root problem is - I'll have a look at what the Architecture options should be to work properly with Launchpad autobuilds. I really appreciate your advice!

**Comment by artmg** [comment]
The file `debian/control` includes the directive `Architecture: all` to create Architecture-**In**-dependent binaries, which up until now seem to have worked ok. I can modify this to make Architecture-Dependent binaries, so amd64 i386 etc all get their own version of the package using `Architecture:`**`any`** 

Theoretically the only downside is "this is less efficient", so I'll go ahead and make this change. If however this causes issues elsewhere (especially on the more widely used distro versions), then we might need to consider backing this out (or developing more complex `debian/rules` to only do this for Trusty)

**Comment by chemeris** [comment]
It does not really _create_ platform independent binaries, it just marks whatever is in the package as platform independent. E.g. this is used to provide data-only packages which are the same for all platforms, or create packages for scripting languages, which are also platform independent. But if you have a real binary in the package, it must be platform dependent.
Not sure why it was working on 16.04 - probably libcurl and the rest are supplied in both 64-bit and 32-bit versions there by default, so no one noticed that the executable is actually 32-bit. Or Launchpad builder for 16.04 is configured to build 64-bit by default.

**Comment by chemeris** [comment]
I've just updated to the new `nixnote2:amd64` and it works great, thank you. It is a proper 64-bit binary now:

```
$ objdump -f `which nixnote2`

/usr/bin/nixnote2:     file format elf64-x86-64
architecture: i386:x86-64, flags 0x00000112:
EXEC_P, HAS_SYMS, D_PAGED
start address 0x00000000004a334f
```

 I also see that `nixnote2:i386` is available now, which will allow 32-bit users to use it (if there are any).

**Comment by MaciekTalaska** [comment]
I may confirm what @chemeris  is saying. The latest version of NixNote2 works great under 64bit version of 14.04. Thanks a lot!
