### ISSUE TITLE
Problem with Yakkety release

### ISSUE THREAD

**Issue by mhalano** [artmg/nixnote2-packaging#15]
I can't install the latest version (2.0beta10) on Yakkety because needs the package libopencv-highgui2.4v5 and this package isn't available anymore. The correct package which replaces that package is libopencv-highgui2.4-deb0.

**Comment by artmg** [comment]
Added libopencv-highgui2.4-deb0 as optional variant in the Control file Depends directive in 
Commit: https://github.com/artmg/nixnote2-packaging/commit/8c72a2e2ce3dd30bacf605ce274e03efc274316a

According to http://packages.ubuntu.com/yakkety/libopencv-dev the other packages nixnote2 Depends on (e.g. libopencv core) is not affected by this change.

@mhalano please recheck in a few hours if new build in PPA works. You will see if it's ready as https://launchpad.net/~nixnote/+archive/ubuntu/nixnote2-daily will show less than _10 days ago_ on the right and will have a build number greater than _2.0-beta-10-0+**793**_ at the bottom

**Comment by mhalano** [comment]
Works on a system upgraded from 16.04 to 16.10. Now I'm installing on other system and there is new dependency problems. I will report a new bug for that.
