### ISSUE TITLE
Problems with missing dependencies on Yakkety

### ISSUE THREAD

**Issue by mhalano** [artmg/nixnote2-packaging#16]
I tried to install Nixnote2 on Yakkety from repository in a system which doesn't had Nixnote2 before and found this package changes:
libhunspell-1.3-0 -> libhunspell-1.4-0
libavcodec54 -> libavcodec57
libavcodec-extra-56 -> libavcodec-extra57
libavformat56 -> libavformat57
libswscale3 -> libswscale4
Seems this need to be added as dependencies options to install correctly.

**Comment by artmg** [comment]
Thanks for these additional Depends, @mhalano (and thanks for closing the previous issue and raising this separately : ) 

I have just kicked off the new builds so hopefully they will be available for testing very soon.

**Comment by mhalano** [comment]
All seems fine now. I just hope don't appears any low level incompatibility between binary versions.

**Comment by artmg** [comment]
I hope so too. There are now a large number of version options in the dependencies, to fit the various Ubuntu releases. Let's pray they play together well.
Thanks for your testing and feedback, @mhalano
