### ISSUE TITLE
Trusty build fails on Poppler IgnoreCase

### ISSUE THREAD

**Issue by artmg** [artmg/nixnote2-packaging#29]
Trusty (14.04 LTS) builds (32 + 64 bit) fails with `‘IgnoreCase’ is not a member of ‘Poppler::Page’`

Poppler version installed on Trusty `libpoppler-qt5-1 amd64 0.24.5-2ubuntu4.5` dates from 2 January 2014.
Extract from [build log](https://launchpad.net/~nixnote/+archive/ubuntu/nixnote2-daily/+build/13369532/+files/buildlog_ubuntu-trusty-amd64.nixnote2_2.0-release-0+962+62+201709130717~ubuntu14.04.1_BUILDING.txt.gz)
```
gui/plugins/popplerviewer.cpp: In member function ‘void PopplerViewer::findNextPage(QStringList, QList<QRectF>*)’:
gui/plugins/popplerviewer.cpp:161:76: error: ‘IgnoreCase’ is not a member of ‘Poppler::Page’
             QList<QRectF> results = doc->page(page)->search(searchHits[i], Poppler::Page::IgnoreCase);
                                                                            ^
gui/plugins/popplerviewer.cpp: In member function ‘QPixmap PopplerViewer::highlightImage()’:
gui/plugins/popplerviewer.cpp:190:77: error: ‘IgnoreCase’ is not a member of ‘Poppler::Page’
         searchLocations.append(doc->page(currentPage)->search(searchHits[i],Poppler::Page::IgnoreCase));
```

**Comment by artmg** [comment]
Last change to this code was 26th July, replacing
```
QList<QRectF> results = doc->page(page)->search(searchHits[i], Poppler::Page::CaseInsensitive);
```
with
```
//#if QT_VERSION < 0x050000
//  QList<QRectF> results = doc->page(page)->search(searchHits[i], Poppler::Page::CaseInsensitive);
//#else
  QList<QRectF> results = doc->page(page)->search(searchHits[i], Poppler::Page::IgnoreCase);
//#endif
```
https://github.com/baumgarr/nixnote2/commit/3330f9c00e658f61aada23da009f37d24b0da608

**Comment by artmg** [comment]
According to [launchpad build history](https://launchpad.net/%7Enixnote/+archive/ubuntu/nixnote2-daily/+builds?build_state=built&batch=75&memo=75&start=75) the last successful build for trusty was 2017-07-26, making it rather likely it was this commit that makes it fail. Unfortunately the system did not raise an exception at the time.

**Comment by robert7** [comment]
I could try to fix this, if you think this is still needed (actually this also stops me to build the AppImage with Trusty).

**Comment by artmg** [comment]
This repo has now been deprecated, in favour of the debian build inside https://github.com/robert7/nixnote2 (which now seems to avoid using poppler at all) and which has stable builds for Xenial 16.04 LTS.

This issue is being closed as Won't Fix. Apologies

**Comment by robert7** [comment]
I know about it and I will it maybe fix it (but I'm not sure, if it is worth the effort).

**Comment by artmg** [comment]
Trusty LTS only has 6 months left to run, so I doubt it is it worth it

**Comment by robert7** [comment]
ok :)
