### ISSUE TITLE
Help about does not expand __VERSION__ variable

### ISSUE THREAD

**Issue by artmg** [artmg/nixnote2-packaging#6]
When you install from the PPA, then run nixnote2 and pick _Help_ / _About_ from the menu, it simply displays **`__VERSION__`** rather than saying what the version actually IS

**Comment by vitaleon** [comment]
To fix this simply uncomment line 36 in rules. But replace 2.0-beta-4-0+git$(date +%Y%m%d) with desired version. Perhaps  2.0-beta-7-0+$(date +%Y%m%d) or 2.0-beta-7-0+git$(date +%Y%m%d) be enough.

**Comment by artmg** [comment]
Thanks once more @vitaleon - for now I have plumped for **nixnote2-daily+git$(date +%Y%m%d)** just for the moment, to get SOMETHING appearing. However in the longer run I'd like to get this version pulled automatically from the version created in the recipe

waiting for code update to build before testing

**Comment by artmg** [comment]
despite the fact that the code in https://github.com/baumgarr/nixnote2/blob/master/help/about.html says `__VERSION__` this appears as "**nixnote2-daily+**" rather than the fuller version string above

**Comment by artmg** [comment]
trying with 'shell' prefix in rules makefile

**Comment by vitaleon** [comment]
Moreover you can try something like
DEBVER := $(shell dpkg-parsechangelog --show-field Version)
override_dh_auto_build:
                sed -i "s/**VERSION**/$(DEBVER)/" help/about.html
to automatically set version from changelog

**Comment by artmg** [comment]
Daily PPA now correctly displays Help / About version as _nixnote2-daily+YYYYMMDD_

This was achieved by updating the _debian / rules_ file to substitute with the system date at the end of the build process:

```
override_dh_auto_build:
    sed -i "s/__VERSION__/nixnote2-daily+$(shell date +%Y%m%d)/" help/about.html
```

Issue Closed.
