### ISSUE TITLE
merge hosiet Debian build scripts?

### ISSUE THREAD

**Issue by artmg** [artmg/nixnote2-packaging#9]
Investigate @hosiet debian build scripts at https://github.com/hosiet/ppa/tree/master/debuild/nixnote2-2.0%7Ebeta8/debian to see if there are techniques we can use for a combined debian / ubuntu launchpad build (with the possibility of one day merging back into the main baumgarr head?)

**Comment by artmg** [comment]
### different

**rules** - quite a few extra features - are any useful?
changelog - not buamgarr copy, but parallel numbering
control - much shorter build depends list

### same

source/format, compat, copyright (similar), 

### missing

patches

**Comment by hosiet** [comment]
To avoid potential confusion, check out [this repo(http://github.com/hosiet/nixnote2), a clearer example that can build packages using gbp / git-pbuilder / etc.

Looks like upstream is splitting packages. Will follow later, but not in his way.

**Comment by hosiet** [comment]
FYI, my packaging script is now considered stable and ready to be reviewed again by Debian Developers for sponsorship once upstream gives another release tag. You may take a review again for any changes since initial version.

**Comment by artmg** [comment]
Hosiet scripts now integrated into new fork https://github.com/robert7/nixnote2 and this repo is being deprecated
